
DROP TYPE IF EXISTS roles CASCADE;

DROP TYPE IF EXISTS user_status CASCADE;

DROP TYPE IF EXISTS ride_status CASCADE;

DROP TYPE IF EXISTS vehicle_type CASCADE;

DROP TYPE IF EXISTS ride_event_type CASCADE;

DROP TYPE IF EXISTS driver_status CASCADE;